### ISSUE TITLE
Doubt on the data set 

### ISSUE THREAD

**Issue by Kolaparthi-Vamsi** [ChrisMats/CSAW-S#1]
Hi Chris, 
I am reading through the information in CSAW-S. I am working in LTI and I have been asked to research on a use case where I will need to do image classification of breast cancer(degree classification of breast image) and generate an auto text report. 

For this I will be needing data with images and clinical reports respectively. Please can you guide me with the data set, that will really be a great help. 

Thanks for your time.

**Comment by ChrisMats** [comment]
Hi,

Thanks for reaching out.
Please note that this dataset is for research / academic use only (non-commercial).

This dataset does not include clinical reports and we do not claim that it does!
Please do not use titles that mislead the users.

Thank you
